### ISSUE TITLE
Can you explain the logic behind the blocks and their rotation?

### ISSUE THREAD

**Issue by arctop-sk** [ShockWave2048/Tetris#2]
Hi!.

I was playing around with the project for learning purposes, and I don't understand how you setup the blocks and rotations patterns. what do the numbers represent? how do you rotate? I'm asking since i'm seeing issues, like S / Z don't look different and are able to rotate into one another, and some L's don't correctly rotate, so I'm a bit confused as to the logic.

**Comment by ShockWave2048** [comment]
Hi!

Single block pattern is field 4x4 cells, integers are coordinations (of cells) in this field -> [x1,y1,x2,y2,x3,y3,x4,y4]

Rotation is chain of mirror and swap coords of array of block, example -> rotate by 90 degree clockwise from zero (default) -> take zero rotation pattern -> swap coords (x<->y) -> mirror horizontally.

So it take clear source pattern, and set to current rotation 0(0), 90(1), 180(2), 270(3) degrees (SWITCH-CASE block in rotate() method).

Hope this help you.

**Comment by arctop-sk** [comment]
thank you.
